### ISSUE TITLE
question about webview

### ISSUE THREAD

**Issue by GrigoriyGriMor** [zouloux/unity-web-view#1]
Hi, I'm a novice developer, and I want to implement webview into my PC game using your plugin.

I did everything according to the instructions, but I get an error: Webview is not supported on this platform.
Unity Engine.Debug:LogError (object)

Then it outputs two logs: Writing file... C:/Users/wertt/AppData/LocalLow/DefaultCompany/NNKTest\yandex.html

Loading web view index ...

I really need help, I hope you will answer soon.

**Comment by zouloux** [comment]
Hello 👋
This project is kind of old but it may still work. But if I remember well, the only supported platforms are iOS and Android, no desktop PC / Mac. You can only test it in the Unity simulator on a desktop env, but not export it.
This is a limitation of https://github.com/gree/unity-webview ( the readme say, Window not supported for now )
I searched quickly in the issues of this repo and found this : https://github.com/gree/unity-webview/issues/586#issuecomment-680917028
Good luck ✌️
